#!/bin/sh

echo "Content-Type: text/html"
echo ""
echo "<html>"
echo "<head><title>CGI demo</title></head>"
echo "<body>"
echo "<h1>Hello from CGI!</h1>"
echo "<p>This HTML was generated by a program.</p>"
echo "</body>"
echo "</html>"

