name: Build and Deploy Python Azure Function - lab8-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure/functions/monte-karlo' 
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Validate requirements.txt
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          pip install -r requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D24A7B4A71204F84B13D647BCDAC94A3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EE8CD8BA27CC4384AC48FBB92C85E081 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A12685D133B349B39969A354DA96060F }}

      - name: Set app settings
        run: |
          az functionapp config appsettings set \
            --name lab8-func \
            --resource-group epam-avk-lab01-dev-resources \
            --settings STORAGE_ACCOUNT_NAME=sgeb001account          

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'lab8-func'
          slot-name: 'Production'
          package: ./app
          
